package icaro.infraestructura.patronAgenteReactivo.percepcion.factoriaEInterfaces;

import icaro.infraestructura.entidadesBasicas.interfaces.InterfazGestionPercepcion;

public abstract class PercepcionAbstracto implements ItfConsumidorPercepcion, ItfProductorPercepcion, InterfazGestionPercepcion {
}
