//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.04 at 04:19:28 PM CEST 
//


package icaro.infraestructura.entidadesBasicas.descEntidadesOrganizacion.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DescComportamientoAgenteCognitivo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescComportamientoAgenteCognitivo">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:icaro:aplicaciones:descripcionOrganizaciones}DescComportamientoAgente">
 *       &lt;sequence>
 *         &lt;element name="rutaReglas" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescComportamientoAgenteCognitivo", propOrder = {
    "rutaReglas"
})
public class DescComportamientoAgenteCognitivo
    extends DescComportamientoAgente
{

    protected String rutaReglas;

    /**
     * Gets the value of the rutaReglas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRutaReglas() {
        return rutaReglas;
    }

    /**
     * Sets the value of the rutaReglas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRutaReglas(String value) {
        this.rutaReglas = value;
    }

}
