//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.04 at 04:19:28 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:icaro:aplicaciones:descripcionOrganizaciones", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package icaro.infraestructura.entidadesBasicas.descEntidadesOrganizacion.jaxb;
